#include "pch.hpp"

#include "core_entry_point.cpp"
#include "pch.cpp"
#include "processor.cpp"
#include "file_system\file_system.cpp"
#include "logging\log.cpp"
#include "memory\StdMalloc.cpp"
#include "memory\hacky_memory_override_release.cpp"
#include "memory\memory.cpp"
#include "memory\memory_manager.cpp"
#include "memory\page_allocator.cpp"
#include "modules\startup_initializer.cpp"
#include "object\garbage_collector.cpp"
#include "parallelism\Mutex_linux.cpp"
#include "parallelism\Mutex_win.cpp"
#include "parallelism\Semaphore_win.cpp"
#include "parallelism\TaskSystem.cpp"
// #include "parallelism\TaskSystem_win.cpp" errors ;c
#include "raytl\array.cpp"
#include "raytl\string.cpp"
#include "threading\lock_win32.cpp"
#include "threading\threading.cpp"
#include "threading\thread_win32.cpp"
// #include "windows\platform_fs.cpp" errors ;c
#include "windows\platform_memory.cpp"
#include "windows\platform_processor.cpp"